export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_LOADING = 'FETCH_FORECAST_LOADING;'; 
export const FETCH_FORECAST_ERROR = 'FETCH_FORECAST_ERROR';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';